package mobilesdkdemo.rbbn.itswinter.audio.model;

public class Track {
        private int idTrack;
        private int idAlbum;
    private int idArtist;
    private int idLyric;
    private String idIMVDB;
    private String strTrack;
    private String strAlbum;
    private String strArtist;
    private String strArtistAlternate;
    private int intCD;
    private int intDuration;
    private String strGenre;
    private String strMood;
    private String strStyle;
    private String strTheme;
    private String strDescriptionEN;
    private String strTrackThumb;
    private String strTrack3DCase;
    private String strTrackLyrics;
    private String strMusicVid;
    private String strMusicVidDirector;
    private String strMusicVidCompany;
    private String strMusicVidScreen1;
    private String strMusicVidScreen2;
    private String strMusicVidScreen3;
    private int intMusicVidViews;
    private int intMusicVidLikes;
    private int intMusicVidDislikes;
    private int intMusicVidFavorites;
    private int intMusicVidComments;
    private int intTrackNumber;
    private int intLoved;
    private int intScore;
    private int intScoreVotes;
    private int intTotalListeners;
    private int intTotalPlays;
    private String strMusicBrainzID;
    private String strMusicBrainzAlbumID;
    private String strMusicBrainzArtistID;
    private String strLocked;
}
